name: GitHub Snake Animation

on:
  push:
    branches:
      - main

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: platane/snk@v3.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: ./output/github-contribution-grid-snake.svg

      - name: Commit and Push Snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Update GitHub snake animation" || echo "No changes to commit"
          git push
